import { Geist, Geist_Mono } from "next/font/google";
// surpress global css warning

import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Metadata } from "next";
import { Navbar1 } from "@/components/navbar1";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          storageKey="theme"
          >
            <Toaster closeButton richColors position={"top-center"} expand={false} />
            <Suspense>
              <div className="flex lg:min-w-screen w-full justtify-start lg:justify-center bg-white dark:bg-black">
                <Navbar1/>
              </div>
            </Suspense>
            <main className="flex min-h-screen w-full bg-white dark:bg-black">
              <div className="flex-row">
                {children}
              </div>
            </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
